# Generated by Django 3.1 on 2021-08-19 22:48

from django.db import migrations
from usersapp.utils import geek_user_generator


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    GeekUser = apps.get_model('usersapp', 'GeekUser')
    db_alias = schema_editor.connection.alias
    user_data = geek_user_generator()
    GeekUser.objects.using(db_alias).bulk_create([
        GeekUser(**next(user_data)) for _ in range(10)
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates a few regular user instances,
    # so reverse_func() should delete them.
    GeekUser = apps.get_model('usersapp', 'GeekUser')
    db_alias = schema_editor.connection.alias
    GeekUser.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
