# Generated by Django 3.1 on 2021-08-28 22:23
from random import choice, randint

from django.db import migrations


NAMES = ('Amphitruo', 'Asinaria', 'Miles gloriosus', 'Mostellaria', 'Captivi',
    'Cistellaria', 'Curculio', 'Epidicus', 'Trinummus', 'Truculentus',
    'Mercator', 'Pseudolus', 'Poenulus')


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Project = apps.get_model('notesapp', 'Project')
    GeekUser = apps.get_model('usersapp', 'GeekUser')
    db_alias = schema_editor.connection.alias
    Project.objects.using(db_alias).bulk_create([
        Project(name=choice(NAMES)) for _ in range(5)
    ])
    for project in Project.objects.using(db_alias).all():
        for user in GeekUser.objects.using(db_alias).exclude(is_superuser=True).order_by('?')[:randint(1, 5)]:
            project.users.add(user)


def reverse_func(apps, schema_editor):
    # forwards_func() creates a few regular user instances,
    # so reverse_func() should delete them.
    Project = apps.get_model('notesapp', 'Project')
    db_alias = schema_editor.connection.alias
    Project.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
        ('usersapp', '0002_fill_users'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
