# Generated by Django 3.1 on 2021-08-28 23:01
from random import choices, randint

from django.db import migrations


TEXT = """Alea jacta est.
Amicus cognoscitur amore, more, ore, re.
Aqua cavat lapidem non vi, sed saepe cadendo.
Asinus asinorum in saecula saeculorum.
Barba crescit caput nescit.
Bellum omnium contra omnes.
Bona fama divitiis est potior.
Carum est quod rarum est.
Charta non erubescit.
Chorus magno cursum rapit effera.
Concordia parvae res crescunt, discordia maximae dilabuntur.
Consuetudo altera natura.
Debes ergo potes.
Deus ex machina.
Dictum est factum.
Ego cogito ergo sum.
Errare humanum est, sed stultum est in errore perseverare.
Experientia est optima magistra.
Felix qui nihil debet.
Hic sunt dracones.
Hoc volo, sic jubeo, sit pro ratione voluntas.
Homo sum et nihil humani a me alienum puto.
Honores mutant mores, sed raro in meliores.
Ignorantia non est argumentum.
Multum, non multa.
Nihil habenti nihil deest.
Nemo omnia potest scire.
"""


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Note = apps.get_model('notesapp', 'Note')
    Project = apps.get_model('notesapp', 'Project')
    db_alias = schema_editor.connection.alias
    Note.objects.using(db_alias).bulk_create([
        Note(
            project=project,
            author=project.users.order_by('?').first(),
            body=' '.join(choices(TEXT.split('\n'), k=randint(2, 4)))
        )
        for project in Project.objects.using(db_alias).all()
        for _ in range(randint(3, 5))
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates a few regular user instances,
    # so reverse_func() should delete them.
    Note = apps.get_model('notesapp', 'Note')
    db_alias = schema_editor.connection.alias
    Note.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_fill_projects'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
